Testing
YunoHost-Apps/shaarli_ynh pull request #58
Opened 2020-11-03 08:53 UTC by lapineige

#57 : Updated to V0.12.0 and Nginx fix

2020-11-10 17:50 UTC, ericgaspar requested changes
Quick review...
You can also remove the comments on install script...

2020-11-10 17:50 UTC, ericgaspar commented on issue_template.md
> +    sudo yunohost app install REPLACEBYYOURAPP
```suggestion
    sudo yunohost app install shaarli
```

2020-11-10 17:50 UTC, ericgaspar commented on scripts/_common.sh
> +extra_php_dependencies="php${YNH_PHP_VERSION}-cli php${YNH_PHP_VERSION}-gettext php${YNH_PHP_VERSION}-curl php${YNH_PHP_VERSION}-intl php${YNH_PHP_VERSION}-gd php${YNH_PHP_VERSION}-mbstring openssl"
```suggestion
YNH_PHP_VERSION="7.3"

# dependencies used by the app
pkg_dependencies="openssl"

extra_php_dependencies="php${YNH_PHP_VERSION}-cli php${YNH_PHP_VERSION}-gettext php${YNH_PHP_VERSION}-curl php${YNH_PHP_VERSION}-intl php${YNH_PHP_VERSION}-gd php${YNH_PHP_VERSION}-mbstring"
```
`openssl` in not a PHP package so better to install it with `pkg_dependencies`

2020-11-21 09:42 UTC, anmol26s commented
Why is  CI failing?

2020-11-24 14:02 UTC, alexAubin approved these changes
Super quick review, LGTM

2020-11-24 14:48 UTC, lapineige commented
@anmol26s I don't get it https://ci-apps-dev.yunohost.org/jenkins/job/shaarli_ynh%20PR58%20(ericgaspar)/lastBuild/console

2020-11-24 15:21 UTC, alexAubin commented
@lapineige : uh yeah for some reason it looks like the CI fails to reach the app after the (successful) installation:

```
Try to access by url...
curl: (47) Maximum (50) redirects followed
```

Dunno if that's due to the CI somehow or if an human is able to reproduce the issue...

2020-11-24 15:26 UTC, ericgaspar commented
I think the app is redirected (to a first logging post-install panel) and NGINX is not configured to redirect.

You can implement the cURL post-install explained by Kayou on this issue for Mantis:
https://github.com/YunoHost-Apps/mantis_ynh/pull/6
and the code:
https://github.com/YunoHost-Apps/mantis_ynh/blob/e7a1f471d813a829558fe426aa21beb124f76727/scripts/install#L121-L137
This will skip the post installation panel (and also the 302 on NGINX)

Another solution could be perhaps to add a proxy_redirect in the NGINX configuration ...

2020-11-24 17:01 UTC, lapineige commented
I don't understand all of that, does it concerns only CI or this app too ?

2020-11-24 18:12 UTC, ericgaspar commented
I think this is a problem with the NGINX config ...

2020-11-24 18:39 UTC, ericgaspar commented
@lapineige I pushed Patch2 which should fix some errors

2020-11-24 23:45 UTC, tituspijean commented
So, I have investigated the issue with the `Too many redirects`. It happens due to Shaarli making the browser go back and forth between `/install` and `/install/session-test`. (I suspect it is a feature, not a bug, but I fail to see *why* they check for a session that way).

If we reinstate `conf/config.json.php`, the postinstall will be ignored and redirects loop will never be triggered. We need to update this file though, and put the placeholders `sed`s (or `--other_vars`) back in `install` and `upgrade`.

2020-11-25 09:04 UTC, lapineige commented
I'll trust you on this one, this is beyond my knowledge in yunohost packaging and nginx stuff

2020-11-26 11:56 UTC, tituspijean commented
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/shaarli_ynh%20PR58%20(tituspijean)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/shaarli_ynh%20PR58%20(tituspijean)/) as of 9a949c1.

2020-11-27 04:42 UTC, alexAubin approved these changes
Super quick review, LGTM

2020-11-30 08:33 UTC, ericgaspar approved these changes

2020-11-30 08:43 UTC, merged